server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /ru/index.html;
    }

    location = /ru {
        return 302 /ru/index.html;
    }

    location = /en {
        return 302 /en/index.html;
    }

    location = /es {
        return 302 /es/index.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
